export const APP_CONFIG = {
  year: 2026,
  periodLabel: "Январь 2026",
  actualMonthIndex: 1,
  defaultMonthIndex: 0,
  contactUrl: "https://max.ru/id7718084994_bot",
  data: {
    universities: "data/universities.json",
    ratingsJson: "data/ratings-2026.json",
    ratingsXlsx: "data/ratings-2026.xlsx",
  },
  months: [
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь",
  ],
  categories: [
    { id: "consolidated", label: "Сводный рейтинг", column: "Сводный рейтинг" },
    { id: "smi", label: "СМИ", column: "СМИ" },
    { id: "social", label: "Социальные сети", column: "Социальные сети" },
    { id: "vk", label: "ВКонтакте", column: "ВКонтакте", parent: "social" },
    { id: "tg", label: "Telegram", column: "Telegram", parent: "social" },
    { id: "ok", label: "MAX", column: "MAX", parent: "social" },
    { id: "rt", label: "Rutube", column: "Rutube", parent: "social" },
    { id: "site", label: "Сайт", column: "Сайт" },
    { id: "agenda", label: "Федеральная повестка", column: "Федеральная повестка" },
  ],
  limits: [5, 10, 50, "all"],
};
